// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLNsY_xwMNw9fn6TJgXhETTyne8PxLcOM',
    appId: '1:396836003350:web:e0765730ff4f8127af1f37',
    messagingSenderId: '396836003350',
    projectId: 'jumapp-7786d',
    authDomain: 'jumapp-7786d.firebaseapp.com',
    storageBucket: 'jumapp-7786d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4LGSw_6-bhYB7X-txd6sL-VpP_S9aJlc',
    appId: '1:396836003350:android:1022921842a2c55eaf1f37',
    messagingSenderId: '396836003350',
    projectId: 'jumapp-7786d',
    storageBucket: 'jumapp-7786d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_BkaarPCKLRp9DwnfS1JJ1xzvOT-NrE',
    appId: '1:396836003350:ios:8ff8a96c733395deaf1f37',
    messagingSenderId: '396836003350',
    projectId: 'jumapp-7786d',
    storageBucket: 'jumapp-7786d.appspot.com',
    iosClientId: '396836003350-saq8adsm6bagbi60c7glpnodq4eet6mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jumApp',
  );
}
